=== LightAurore/JAVASCRIPT-FULL/xml/exo-02/listCharacterDTD.dtd
<!ELEMENT listCharacter (Character)>
	<!ELEMENT Character (Name, FirstName?, Class, Level)>
	<!ATTLIST Character key ID #REQUIRED>
	<!ATTLIST Character brother IDREF #IMPLIED>
	<!ELEMENT FirstName (#PCDATA)>
	<!ELEMENT Class (#PCDATA)>
	<!ELEMENT Level (#PCDATA) >

=== LightAurore/JAVASCRIPT-FULL/xml/xml-pratique/exo-dtd/listCharacterDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE listCharacter SYSTEM "listCharacterDTD.dtd">


<listCharacter>
	<Character key="character01" brother="character01">
		<Name>Majere</Name>
		<FirstName>Raistlin</FirstName>
		<Class>Wizard</Class>
		<Level>48</Level>
	</Character>
	
	<Character key="character05" brother="character05">
		<Name>Artur</Name>
		<FirstName>Caramon</FirstName>
		<Class>Warrior</Class>
		<Level>43</Level>
	</Character>
	
	<Character key="character06">
		<Name>Duck</Name>
		<FirstName>Della</FirstName>
		<Class>Mage</Class>
		<Level>42</Level>
	</Character>
</listCharacter>
