=== LightAurore/JAVASCRIPT-FULL/xml/xml-pratique/book-schema/monbookschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<lib:schema xmlns:lib="http://www.w3.org/2001/XMLSchema">

<!-- 

    <lib:element name="books">

        <lib:complexType>

            <lib:all>

                <lib:element name="book" maxOccurs="unbounded">

                    <lib:complexType>
                        <lib:sequence>
                            <lib:element name="title" type="lib:string"/>

                            <lib:element name="author">
                                <lib:complexType>

                                </lib:complexType>
                            </lib:element>

                            <lib:element name="genre" type="lib:string"/>

                            <lib:element name="publication" type="lib:integer"/>

                            <lib:element name="serie">
                                <lib:complexType>
                                    <lib:simpleContent>
                                        <lib:extension base="lib:string">
                                            <lib:attribute name="number" type="lib:integer"/>
                                        </lib:extension>
                                    </lib:simpleContent>
                                </lib:complexType>
                            </lib:element>

                        </lib:sequence>
                    </lib:complexType>
                </lib:element>
            </lib:all>
        </lib:complexType>


    </lib:element> -->

    <!-- type -->
    <lib:simpleType name="date-format">
        <lib:restriction base="lib:string">
            <lib:enumeration value="dd/mm/yyyy" />
            <lib:enumeration value="mm/dd/yyyy" />
            <lib:enumeration value="yyyy/mm/dd" />
        </lib:restriction>
    </lib:simpleType>
    <lib:simpleType name="gender">
        <lib:restriction base="lib:string">
            <lib:enumeration value="m" />
            <lib:enumeration value="f" />
            <lib:enumeration value="x" />
        </lib:restriction>
    </lib:simpleType>


    <!-- element -->
    <lib:element name="name">
        <lib:complexType>
            <lib:attribute name="firstname" type="lib:string" use="required" />
            <lib:attribute name="lastname" type="lib:string" use="required" />
        </lib:complexType>
    </lib:element>

    <lib:element name="birthdate">
        <lib:complexType>
            <lib:simpleContent>
                <lib:extension base="lib:string">
                    <lib:attribute name="format" type="date-format"/>
                </lib:extension>
            </lib:simpleContent>
        </lib:complexType>
    </lib:element>


    <lib:element name="author">
        <lib:complexType>
            <lib:all>
                <lib:element ref="name"/>
                <lib:element ref="birthdate"/>
                <lib:element name="gender" type="gender"/>
            </lib:all>
        </lib:complexType>
    </lib:element>

    <lib:element name="serie">
        <lib:complexType>
            <lib:simpleContent>
                <lib:extension base="lib:string">
                    <lib:attribute name="number" type="lib:positiveInteger" />
                </lib:extension>
            </lib:simpleContent>
        </lib:complexType>
    </lib:element>
    
    <lib:element name="book">
        <lib:complexType>
            <lib:sequence>
                <lib:element name="title" type="lib:string" />
                <lib:element ref="author" />
                <lib:element name="genre" type="lib:string" />
                <lib:element name="publication" type="lib:string" />
                <lib:element ref="serie" minOccurs="0" />
            </lib:sequence>
        </lib:complexType>
    </lib:element>

    <lib:element name="books">
        <lib:complexType>
            <lib:sequence>
                <lib:element ref="book" maxOccurs="unbounded" />
            </lib:sequence>
        </lib:complexType>
    </lib:element>


</lib:schema>

=== LightAurore/JAVASCRIPT-FULL/xml/xml-pratique/book-schema/book.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./monbookschema.xsd">
    <book>
        <title>Le Nom du vent</title>
        <author>
            <name firstname="Patrick" lastname="Rothfuss" />
            <birthdate format="dd/mm/yyyy">06/06/1973</birthdate>
            <gender>m</gender>
        </author>
        <genre>Fantasy</genre>
        <publication>2007</publication>
        <serie number="1">Chronique du tueur de roi</serie>
    </book>
    <book>
        <title>Le Petit Prince</title>
        <author>
            <name firstname="Antoine" lastname="de Saint-Exupéry" />
            <birthdate format="dd/mm/yyyy">29/06/1900</birthdate>
            <gender>m</gender>
        </author>
        <genre>Conte philosophique</genre>
        <publication>1943</publication>
    </book>
    <book>
        <title>Harry Potter à l’école des sorciers</title>
        <author>
            <name firstname="J.K." lastname="Rowling" />
            <birthdate format="dd/mm/yyyy">31/07/1965</birthdate>
            <gender>f</gender>
        </author>
        <genre>Fantasy</genre>
        <publication>1997</publication>
        <serie number="2">Harry Potter</serie>
    </book>
    <book>
        <title>La Servante écarlate</title>
        <author>
            <name firstname="Margaret" lastname="Atwood" />
            <birthdate format="dd/mm/yyyy">18/11/1939</birthdate>
            <gender>f</gender>
        </author>
        <genre>Science-fiction dystopique</genre>
        <publication>1985</publication>
        <serie number="3">Le Testament</serie>
    </book>
    <book>
        <title>Harry Potter et la chambre des secrets</title>
        <author>
            <name firstname="J.K." lastname="Rowling" />
            <birthdate format="dd/mm/yyyy">31/07/1965</birthdate>
            <gender>f</gender>
        </author>
        <genre>Fantasy</genre>
        <publication>1998</publication>
        <serie number="4">Harry Potter</serie>
    </book>
</books>
